"""create_vehicles_and_maintenance_records

Revision ID: 71080326941d
Revises: 
Create Date: 2026-06-19 15:44:13.324044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71080326941d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_make'), ['make'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_records')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_make'))
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))

    op.drop_table('vehicles')
    # ### end Alembic commands ###