"""initial migration

Revision ID: b0f3513c50ff
Revises: 
Create Date: 2026-06-20 16:05:26.575322

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b0f3513c50ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_make'), ['make'], unique=False)

    op.create_table('maintenancerecord',
    sa.Column('maintenance_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenancerecord')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_make'))
        batch_op.drop_index(batch_op.f('ix_vehicle_license_plate'))

    op.drop_table('vehicle')
    # ### end Alembic commands ###