"""addition of new columns

Revision ID: b15d12e4f6c7
Revises: 
Create Date: 2026-06-20 18:20:35.045254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b15d12e4f6c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_mileage', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.Enum('PETROL', 'DIESEL', 'ELECTRIC', 'HYBRID', name='fueltype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_make'), ['make'], unique=False)

    op.create_table('maintenancerecord',
    sa.Column('maintenance_type', sa.Enum('OIL_CHANGE', 'TIRE_ROTATION', 'BRAKE_SERVICE', 'BATTERY_REPLACEMENT', 'ENGINE_TUNE_UP', 'AIR_FILTER_REPLACEMENT', 'GENERAL_INSPECTION', 'OTHER', name='maintenancetype'), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('mileage_at_service', sa.Integer(), nullable=False),
    sa.Column('service_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('next_service_due_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warranty_covered', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenancerecord')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_make'))
        batch_op.drop_index(batch_op.f('ix_vehicle_license_plate'))

    op.drop_table('vehicle')
    # ### end Alembic commands ###